test macos signature

diff --git a/.github/workflows/macos-build.yml b/.github/workflows/macos-build.yml
--- a/.github/workflows/macos-build.yml
+++ b/.github/workflows/macos-build.yml
@@ -1,10 +1,10 @@
 name: Macos Tests
 
-on: [workflow_dispatch]
-      
+on: [ workflow_dispatch ]
+
 env:
   BIN_SUFFIX: macos
-	
+
 jobs:
   test:
     runs-on: macos-latest
@@ -26,20 +26,20 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
       - name: Testing
         run: |
-           ./mvnw clean -PnativeTest test -Pnative native:compile
-        
+          ./mvnw clean -PnativeTest test -Pnative native:compile
+
       - name: Signature
         env:
           GPG_PUBID: ${{ secrets.GPG_PUBID }}
-        working-directory: target 
+        working-directory: target
         run: |
-           gpg --armor --detach-sign props-$BIN_SUFFIX
-           gpg --keyserver keyserver.ubuntu.com --recv-keys $GPG_PUBID
-           gpg --armor --export 'opcal <opcal.xyz@outlook.com>' > Release.asc
+          gpg --armor --detach-sign props-$BIN_SUFFIX
+          gpg --keyserver keyserver.ubuntu.com --recv-keys $GPG_PUBID
+          gpg --armor --export 'opcal <opcal.xyz@outlook.com>' > Release.asc
       - name: Verify
         run: |
-           gpg --import ./target/Release.asc
-           gpg --verify ./target/props-$BIN_SUFFIX.asc ./target/props-$BIN_SUFFIX || echo "verify failed"
-           ls -lah ./target/
+          gpg --import ./target/Release.asc
+          gpg --verify ./target/props-$BIN_SUFFIX.asc ./target/props-$BIN_SUFFIX || echo "verify failed"
+          ls -lah ./target/
 
            
